[package]
name    = "flexinput-virtual"
version.workspace = true
edition.workspace = true

[dependencies]
flexinput-core = { workspace = true }

[target.'cfg(windows)'.dependencies]
vigem-client = { version = "0.1", features = ["unstable_ds4", "unstable_xtarget_notification"] }
enigo = "0.2"
flexinput-hidmaestro = { workspace = true }

[dev-dependencies]
glam = { workspace = true }
